export const VERSION = '0.1.0'

export * from './domain/index.js'
export * from './ports/index.js'
export * from './text/index.js'
export * from './core/index.js'
export * from './adapters/rule-based/index.js'
export * from './adapters/fuzzy/index.js'
export * from './adapters/web-speech/index.js'
export * from './embedded.js'
